name: todo cicd

on:
    push:
        branches:
            - main
        paths:
            - 'todo/**'

jobs:
    build-scan-push_CI:
        runs-on: ubuntu-latest
        steps:
            - name: checkout code
              uses: actions/checkout@v3

            - name: docker login
              run: echo ${{ secrets.DOCKER_PASSWORD }} | docker login -u ${{ secrets.DOCKER_USERNAME }} --password-stdin

            - name: docker build
              run: | 
                docker build \
                --build-arg DB_ENGINE="${{ secrets.DB_ENGINE }}" \
                --build-arg DB_USER="${{ secrets.DB_USER }}" \
                --build-arg DB_NAME="${{ secrets.DB_NAME }}" \
                --build-arg DB_PASSWORD="${{ secrets.DB_PASSWORD }}" \
                --build-arg DB_PORT="${{ secrets.DB_PORT }}" \
                --build-arg DB_HOST="${{ secrets.DB_HOST }}" \
                -t ${{ secrets.DOCKER_USERNAME }}/todo-web:${{ github.sha }} \
                todo/.

                echo "✅✅Docker image built ✅✅"

            - name: Scan Docker image using Trivy 
              uses: aquasecurity/trivy-action@master
              with:
                image-ref: '${{ secrets.DOCKER_USERNAME }}/todo-web:${{ github.sha }}'
                format: 'table'
                exit-code: '0'       
                severity: 'CRITICAL,HIGH'
              continue-on-error: true

            - name: docker push 
              run: | 
                docker push ${{ secrets.DOCKER_USERNAME }}/todo-web:${{ github.sha }}
                echo "✅✅Docker image pushed ✅✅"

    Deploy:
        needs: build-scan-push_CI
        runs-on: ubuntu-latest
        steps: 
            - name: login to server(ec2)
              uses: appleboy/ssh-action@master
              with:
                host: ${{ secrets.EC2_HOST }}
                username: ${{ secrets.EC2_USERNAME }}
                key: ${{ secrets.EC2_SSH_KEY }}
                script: |
                    echo "✅✅ssh connected✅✅"
                    cd workspace/django-projects/todo
                    echo ${{ secrets.DOCKER_PASSWORD }} | docker login -u ${{ secrets.DOCKER_USERNAME }} --password-stdin
                    docker pull ${{ secrets.DOCKER_USERNAME }}/todo-web:${{ github.sha }}
                    export TAG=${{ github.sha }}
                    echo "TAG=$TAG" >> .env
                    docker compose down
                    docker compose up -d
                    docker image prune -af
                    echo "✅✅Docker image deployed✅✅"